// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.12.3
// source: defaultcmd.proto

package cmdpb

import (
	context "context"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

var File_defaultcmd_proto protoreflect.FileDescriptor

var file_defaultcmd_proto_rawDesc = []byte{
	0x0a, 0x10, 0x64, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x63, 0x6d, 0x64, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x05, 0x63, 0x6d, 0x64, 0x70, 0x62, 0x1a, 0x0d, 0x64, 0x65, 0x66, 0x61, 0x75,
	0x6c, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x32, 0x4c, 0x0a, 0x0d, 0x64, 0x65, 0x66, 0x61,
	0x75, 0x6c, 0x74, 0x63, 0x6d, 0x64, 0x73, 0x72, 0x76, 0x12, 0x3b, 0x0a, 0x0c, 0x44, 0x65, 0x66,
	0x61, 0x75, 0x6c, 0x74, 0x43, 0x6d, 0x64, 0x44, 0x6f, 0x12, 0x15, 0x2e, 0x63, 0x6d, 0x64, 0x70,
	0x62, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x12, 0x2e, 0x63, 0x6d, 0x64, 0x70, 0x62, 0x2e, 0x44, 0x65, 0x66, 0x61, 0x75, 0x6c, 0x74,
	0x52, 0x65, 0x73, 0x70, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x3b, 0x63, 0x6d, 0x64, 0x70,
	0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var file_defaultcmd_proto_goTypes = []interface{}{
	(*DefaultRequest)(nil), // 0: cmdpb.DefaultRequest
	(*DefaultResp)(nil),    // 1: cmdpb.DefaultResp
}
var file_defaultcmd_proto_depIdxs = []int32{
	0, // 0: cmdpb.defaultcmdsrv.DefaultCmdDo:input_type -> cmdpb.DefaultRequest
	1, // 1: cmdpb.defaultcmdsrv.DefaultCmdDo:output_type -> cmdpb.DefaultResp
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_defaultcmd_proto_init() }
func file_defaultcmd_proto_init() {
	if File_defaultcmd_proto != nil {
		return
	}
	file_default_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_defaultcmd_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_defaultcmd_proto_goTypes,
		DependencyIndexes: file_defaultcmd_proto_depIdxs,
	}.Build()
	File_defaultcmd_proto = out.File
	file_defaultcmd_proto_rawDesc = nil
	file_defaultcmd_proto_goTypes = nil
	file_defaultcmd_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// DefaultcmdsrvClient is the client API for Defaultcmdsrv service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type DefaultcmdsrvClient interface {
	DefaultCmdDo(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*DefaultResp, error)
}

type defaultcmdsrvClient struct {
	cc grpc.ClientConnInterface
}

func NewDefaultcmdsrvClient(cc grpc.ClientConnInterface) DefaultcmdsrvClient {
	return &defaultcmdsrvClient{cc}
}

func (c *defaultcmdsrvClient) DefaultCmdDo(ctx context.Context, in *DefaultRequest, opts ...grpc.CallOption) (*DefaultResp, error) {
	out := new(DefaultResp)
	err := c.cc.Invoke(ctx, "/cmdpb.defaultcmdsrv/DefaultCmdDo", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DefaultcmdsrvServer is the server API for Defaultcmdsrv service.
type DefaultcmdsrvServer interface {
	DefaultCmdDo(context.Context, *DefaultRequest) (*DefaultResp, error)
}

// UnimplementedDefaultcmdsrvServer can be embedded to have forward compatible implementations.
type UnimplementedDefaultcmdsrvServer struct {
}

func (*UnimplementedDefaultcmdsrvServer) DefaultCmdDo(context.Context, *DefaultRequest) (*DefaultResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DefaultCmdDo not implemented")
}

func RegisterDefaultcmdsrvServer(s *grpc.Server, srv DefaultcmdsrvServer) {
	s.RegisterService(&_Defaultcmdsrv_serviceDesc, srv)
}

func _Defaultcmdsrv_DefaultCmdDo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DefaultRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DefaultcmdsrvServer).DefaultCmdDo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/cmdpb.defaultcmdsrv/DefaultCmdDo",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DefaultcmdsrvServer).DefaultCmdDo(ctx, req.(*DefaultRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Defaultcmdsrv_serviceDesc = grpc.ServiceDesc{
	ServiceName: "cmdpb.defaultcmdsrv",
	HandlerType: (*DefaultcmdsrvServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DefaultCmdDo",
			Handler:    _Defaultcmdsrv_DefaultCmdDo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "defaultcmd.proto",
}
